import Head from 'next/head';
import { sliderL } from 'src/components/animations/slider-L';
import { tarzan } from 'src/components/animations/tarzan';
import { BannerMosaic } from 'src/components/examples/banner-mosaic';
import { BannerTarzan } from 'src/components/examples/banner-tarzan';
import { WaveExample } from 'src/components/examples/waver-example';

export default function Home() {
  return (
    <>
      <Head>
        <title>Magic Box - 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '100px',
            maxWidth: '800px',
          }}
        >
          <div style={{ maxWidth: '300px', margin: '0 auto' }}>
            <WaveExample
              selectedAnim={tarzan}
              rows={2}
              cols={4}
              delay={2000}
              animDelay={100}
            />
          </div>
          <BannerMosaic />
          <WaveExample selectedAnim={sliderL} animDelay={1200} delay={0} />
          <BannerTarzan />
        </div>
      </div>
    </>
  );
}
