import Head from 'next/head';
import { Banner1 } from 'src/components/examples/banner-1';

export default function Home() {
  return (
    <>
      <Head>
        <title>Magic Box - 3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="App">
        {/* <h2>Slider - randomFeeder</h2>
        {selectedFeeder === 'wave' && (
          <WaveExample selectedAnim={anims[selectedAnim]} />
        )}
        {selectedFeeder === 'linear' && (
          <LinearExample selectedAnim={anims[selectedAnim]} />
        )}

        {selectedFeeder === 'random' && (
          <RandomExample selectedAnim={anims[selectedAnim]} />
        )} */}

        <Banner1 />
      </div>
    </>
  );
}
